<?php

return [
    'What is Traitz Tech?' => 'Traitz Tech is a leading technology company that offers innovative solutions and services to help businesses grow and succeed. We specialize in various domains including software development, data analytics, and digital transformation. Our mission is to empower businesses with cutting-edge technology and drive their success in the digital age.',
    'How can I apply for an internship?' => 'You can apply for an internship by visiting our application page and filling out the form with your details. Make sure to provide accurate information. Uploading your resume is optional but recommended. Once your application is submitted, our team will review it and get back to you with further instructions. The application process is straightforward and designed to be user-friendly.',
    'What are the benefits of joining Traitz Tech as an intern?' => 'As an intern at Traitz Tech, you will gain real-world experience by working on innovative projects that have a significant impact. You will have the opportunity to collaborate with experienced professionals and learn from their expertise. Additionally, exceptional interns may receive motivation from our team and even get full-time roles on company projects. Our internship program is designed to foster professional growth and provide valuable networking opportunities.',
    'Is the internship paid?' => 'Interns at Traitz Tech pay a ranging fee depending on the duration of the internship. This fee covers various resources and training provided during the internship. However, exceptional interns may receive additional benefits and opportunities for full-time roles on company projects. The fee structure is designed to ensure that interns receive the best possible training and support during their time with us.',
    'What is the duration of the internship?' => 'The duration of the internship varies depending on the role and project, but typically lasts between 1 to 6 months. During this period, interns will work on real projects and gain hands-on experience in their chosen field. The internship duration is flexible and can be adjusted based on the intern\'s availability and project requirements. We aim to provide a comprehensive learning experience that prepares interns for their future careers.',
    // Add more FAQs here
    'What is the application deadline?' => 'The application deadline varies depending on the internship program. Please check our application page for specific deadlines.',
    'Can international students apply?' => 'Yes, international students are welcome to apply for our internship programs.',
    'What qualifications are required?' => 'The qualifications required vary depending on the internship program. Generally, we look for candidates with relevant academic background and skills.',
    'How will I be notified of my application status?' => 'You will be notified of your application status via email. Please ensure that you provide a valid email address in your application.',
    'What is the selection process?' => 'The selection process includes an initial application review, followed by an interview. Successful candidates will be notified via email.',
    'Can I apply for multiple internship programs?' => 'Yes, you can apply for multiple internship programs. Please submit a separate application for each program.',
    'What is the working hours for interns?' => 'The working hours for interns are typically 9 AM to 5 PM, Monday to Friday. However, this may vary depending on the project requirements.',
    'Is there a dress code for interns?' => 'There is no strict dress code for interns. However, we recommend business casual attire.',
    'Will I receive a certificate upon completion?' => 'Yes, interns will receive a certificate of completion at the end of their internship program.',
    'Are there any opportunities for full-time employment?' => 'Yes, exceptional interns may be offered full-time employment opportunities based on their performance and the availability of positions.',
    'What kind of projects will I work on?' => 'Interns will work on a variety of projects related to their field of study. These projects are designed to provide hands-on experience and practical skills.',
    'Is there any training provided?' => 'Yes, interns will receive training and mentorship from experienced professionals throughout their internship program.',
    'What is the company culture like?' => 'Our company culture is collaborative, innovative, and inclusive. We value diversity and encourage open communication and teamwork.',
    'How can I contact the HR department?' => 'You can contact the HR department by emailing juniorngu@traitz.tech or calling +237 (677 802 114).',
    'What is the company\'s mission?' => 'Our mission is to empower businesses with cutting-edge technology and drive their success in the digital age.',
    'What are the company\'s core values?' => 'Our core values include innovation, integrity, collaboration, and customer satisfaction.',
    'Where is the company located?' => 'Our company is located in Douala, Cameroon. Please visit our contact page for the exact address.',
    'What industries does the company serve?' => 'We serve a variety of industries including finance, healthcare, retail, and technology.',
    'What services does the company offer?' => 'We offer a range of services including software development, data analytics, digital transformation, and IT consulting.',
    'How can I request a demo of your services?' => 'You can request a demo of our services by filling out the form on our demo request page. Our team will get back to you to schedule a demo.',
    'What is the company\'s refund policy?' => 'Our refund policy varies depending on the service. Please refer to our terms and conditions for detailed information.',
    'How can I provide feedback?' => 'You can provide feedback by filling out the feedback form on our website or by contacting our customer support team.',
    'What are the payment options available?' => 'We accept various payment options including credit card, bank transfer, and mobile money. Please refer to our payment page for more details.',
    'How can I track my project progress?' => 'You can track your project progress through our project management portal. You will receive login details once your project is initiated.',
    'What is the company\'s privacy policy?' => 'Our privacy policy outlines how we collect, use, and protect your personal information. Please refer to our privacy policy page for more details.',
    'How can I subscribe to the company\'s newsletter?' => 'You can subscribe to our newsletter by filling out the subscription form on our website. You will receive regular updates and news about our services.',
    'What is the company\'s social media presence?' => 'You can follow us on Facebook, Twitter, LinkedIn, and Instagram for the latest updates and news.',
    'How can I schedule a consultation?' => 'You can schedule a consultation by filling out the form on our consultation request page. Our team will get back to you to confirm the appointment.',
    'What is the company\'s customer support contact?' => 'You can contact our customer support team by emailing support@traitz.tech or calling +237 (677 802 114).',
    'What are the company\'s business hours?' => 'Our business hours are 9 AM to 5 PM, Monday to Friday. Please note that our customer support team is available during these hours.',
    'How can I access the company\'s resources?' => 'You can access our resources by visiting the resources section on our website. This includes whitepapers, case studies, and blog posts.',
    'What is the company\'s approach to sustainability?' => 'We are committed to sustainability and have implemented various initiatives to reduce our environmental impact. Please refer to our sustainability page for more details.',
    'How can I join the company\'s partner program?' => 'You can join our partner program by filling out the application form on our partner program page. Our team will review your application and get back to you with further instructions.',
    'What is the company\'s approach to innovation?' => 'We foster a culture of innovation by encouraging creativity and collaboration. Our team is constantly exploring new technologies and solutions to stay ahead of the curve.',
    'How can I request a quote?' => 'You can request a quote by filling out the form on our request a quote page. Our team will get back to you with a detailed quote based on your requirements.',
    'What is the company\'s approach to data security?' => 'We take data security seriously and have implemented various measures to protect your data. Please refer to our data security page for more details.',
    'How can I access the company\'s API?' => 'You can access our API by visiting the API documentation page on our website. You will find detailed information on how to integrate with our services.',
    'What is the company\'s approach to customer satisfaction?' => 'Customer satisfaction is our top priority. We strive to provide exceptional service and support to ensure that our customers are happy with our solutions.',
    'How can I report an issue?' => 'You can report an issue by contacting our customer support team via email or phone. Our team will investigate the issue and provide a resolution as soon as possible.',
    'What is the company\'s approach to employee development?' => 'We are committed to the professional development of our employees. We offer various training programs and opportunities for career growth.',
    'How can I apply for a job at the company?' => 'You can apply for a job by visiting our careers page and submitting your application. Our HR team will review your application and get back to you with further instructions.',
    'What is the company\'s approach to diversity and inclusion?' => 'We value diversity and inclusion and are committed to creating a workplace that is inclusive and welcoming to all. Please refer to our diversity and inclusion page for more details.',
    'How can I request a product demo?' => 'You can request a product demo by filling out the form on our product demo page. Our team will get back to you to schedule a demo.',
    'What is the company\'s approach to corporate social responsibility?' => 'We are committed to corporate social responsibility and have implemented various initiatives to give back to the community. Please refer to our CSR page for more details.',
    'How can I access the company\'s knowledge base?' => 'You can access our knowledge base by visiting the knowledge base section on our website. This includes articles, tutorials, and FAQs.',
];
